# ~/.tmux.conf
# unbind default prefix and set it to ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# make delay shorter
set -sg escape-time 0
set -g mouse on


#### key bindings ####

# reload config file
# bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded!"

# quickly open a new window
bind N new-window

# synchronize all panes in a window
bind y setw synchronize-panes

# pane movement shortcuts (same as vim)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# enable mouse support for switching panes/windows
# set -g mouse-utf8 on
# set -g mouse on


#### copy mode : vim ####

# set vi mode for copy mode
set -g mode-keys vi
setw -g mode-keys vi

# copy mode using 'Esc'
unbind [
bind Escape copy-mode

# start selection with 'space' and copy using 'y'
# bind -t vi-copy 'y' copy-selection

# paste using 'p'
unbind p
bind p paste-buffer

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Set status bar on
set -g status on

# Update the status line every second
set -g status-interval 1

# Set the position of window lists.
set -g status-justify left # [left | centre | right]

# Set Vi style keybinding in the status line
set -g status-keys vi

# Set the status bar position
set -g status-position bottom # [top, bottom]

# Set status bar background and foreground color.
set -g status-style fg=colour136,bg="#1e1e2e"
set -g status-style fg=colour136,bg="default"

# Set left side status bar length and style
set -g status-left-length 60
set -g status-left-style default

# Display the session name
set -g status-left "#[fg=#89b4fa] 🎨 #S #[default]"

set -ag status-left "#[fg=#b4befe,bg=default,bright]  #(watson status -p) #[default]"

# Display the os version (Mac Os)
#set -ag status-left " #[fg=black] #[fg=green,bright]  #(sw_vers -productVersion) #[default]"

# Display the battery percentage (Mac OS)
set -ag status-right "#[fg=green,bg=default,bright]  #(pmset -g batt | tail -1 | awk '{print $3}' | tr -d ';') #[default]"

# Set right side status bar length and style
#set -g status-right-length 140
set -g status-right-length 170
set -g status-right-style default

# Display the cpu load (Mac OS)
set -g status-right "#[fg=#585b70,bg=default,bright] #(top -l 1 | grep -E "^CPU" | sed 's/.*://') #[default]"

# Display the date
set -ag status-right "#[fg=#fab387,bg=default] %a %d #[default]"

# Display the time
#set -ag status-right "#[fg=colour172,bright,bg=default] ⌚︎%l:%M %p #[default]"
set -ag status-right "#[fg=#f38ba8,bright,bg=default] %H:%M:%S  #[default]"

# Display the hostname
set -ag status-right "#[fg=cyan,bg=default] #[default]"

# Set the inactive window color and style
set -g window-status-style fg="#cdd6f4",bg=default
set -g window-status-format ' #I #W '

# Set the active window color and style
#set -g window-status-current-style fg=black,bg=colour7
set -g window-status-current-style fg="#1e1e2e",bg="#a6e3a1"
set -g window-status-current-format ' #I #W '

#set-option -g status-style bg=default
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# for neovim
set -g @resurrect-strategy-nvim 'session'
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
