-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "carbonized_light"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@keyword.return", { fg = "#a2191f" })
hi(0, "@lsp.mod.defaultLibrary", { link = "Special" })
hi(0, "@lsp.mod.deprecated", { fg = "#a2191f" })
hi(0, "@lsp.type.variable", { fg = "#161616" })
hi(0, "@markup.heading.1.markdown", { fg = "#0043ce" })
hi(0, "@markup.heading.2.markdown", { fg = "#005d5d" })
hi(0, "@markup.heading.3.markdown", { fg = "#6929c4" })
hi(0, "@markup.heading.4.markdown", { fg = "#9f1853" })
hi(0, "@markup.strikethrough", {})
hi(0, "@markup.underline", {})
hi(0, "@symbol", { fg = "#6929c4" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@variable", { fg = "#161616" })
hi(0, "Added", { ctermfg = 2, fg = "#0e6027" })
hi(0, "Beacon", { bg = "#161616" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#ba4e00" })
hi(0, "BufferCurrent", { bg = "#c6c6c6", bold = true, fg = "#161616" })
hi(0, "BufferCurrentIcon", { bg = "#c6c6c6" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#c6c6c6", bold = true, fg = "#a2191f" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#c6c6c6", bold = true, fg = "#6929c4" })
hi(0, "BufferInactive", { bg = "#e0e0e0", fg = "#393939" })
hi(0, "BufferInactiveIcon", { bg = "#e0e0e0" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#e0e0e0", fg = "#a2191f" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#e0e0e0", bold = true, fg = "#6929c4" })
hi(0, "BufferLineBuffer", { fg = "#393939" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#161616" })
hi(0, "BufferLineBufferVisible", { fg = "#161616" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#684e00", fg = "#f4f4f4" })
hi(0, "BufferLineTabSelected", { bg = "#684e00", bold = true, fg = "#f4f4f4" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#684e00", bold = true, fg = "#e0e0e0" })
hi(0, "BufferVisible", { bg = "#e0e0e0", bold = true, fg = "#161616" })
hi(0, "BufferVisibleIcon", { bg = "#e0e0e0" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#e0e0e0", bold = true, fg = "#a2191f" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#e0e0e0", bold = true, fg = "#6929c4" })
hi(0, "Changed", { ctermfg = 6, fg = "#6929c4" })
hi(0, "Character", { fg = "#a2191f" })
hi(0, "CmpItemAbbr", { fg = "#161616" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#6f6f6f" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#684e00" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#684e00" })
hi(0, "CmpItemKind", { bg = "#e0e0e0", fg = "#9f1853" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindText", { link = "Statement" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemMenu", { bg = "#e0e0e0", fg = "#161616" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocFadeOut", { link = "Comment" })
hi(0, "CocMarkdownLink", { fg = "#9f1853" })
hi(0, "CocMenuSel", { bg = "#c6c6c6" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#684e00" })
hi(0, "CocSelectedText", { fg = "#a2191f" })
hi(0, "ColorColumn", { bg = "#e0e0e0" })
hi(0, "Comment", { fg = "#6f6f6f" })
hi(0, "Conceal", { fg = "#0043ce" })
hi(0, "Conditional", { fg = "#6929c4" })
hi(0, "Constant", { fg = "#ba4e00" })
hi(0, "CurSearch", { bg = "#ba4e00", ctermbg = 3, ctermfg = 15, fg = "#e0e0e0" })
hi(0, "Cursor", { bg = "#161616", fg = "#f4f4f4" })
hi(0, "CursorColumn", { bg = "#e0e0e0" })
hi(0, "CursorIM", { bg = "#161616", fg = "#f4f4f4" })
hi(0, "CursorLine", { bg = "#e0e0e0" })
hi(0, "CursorLineFold", { bg = "#e0e0e0", fg = "#005d5d" })
hi(0, "CursorLineNr", { bg = "#e0e0e0", fg = "#393939" })
hi(0, "CursorLineSign", { bg = "#e0e0e0", fg = "#6f6f6f" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#0e6027" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#6929c4" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Title" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "WarningMsg" })
hi(0, "Debug", { fg = "#a2191f" })
hi(0, "Define", { fg = "#6929c4" })
hi(0, "Definitions", { fg = "#0e6027" })
hi(0, "DefinitionsIcon", { fg = "#0043ce" })
hi(0, "Delimiter", {})
hi(0, "DiagnosticError", { ctermfg = 1, fg = "#a2191f" })
hi(0, "DiagnosticFloatingError", { bg = "#e0e0e0", fg = "#a2191f" })
hi(0, "DiagnosticFloatingHint", { bg = "#e0e0e0", fg = "#0043ce" })
hi(0, "DiagnosticFloatingInfo", { bg = "#e0e0e0", fg = "#005d5d" })
hi(0, "DiagnosticFloatingOk", { bg = "#e0e0e0", fg = "#0e6027" })
hi(0, "DiagnosticFloatingWarn", { bg = "#e0e0e0", fg = "#6929c4" })
hi(0, "DiagnosticHint", { ctermfg = 4, fg = "#0043ce" })
hi(0, "DiagnosticInfo", { ctermfg = 6, fg = "#005d5d" })
hi(0, "DiagnosticOk", { ctermfg = 2, fg = "#0e6027" })
hi(0, "DiagnosticSignError", { link = "DiagnosticFloatingError" })
hi(0, "DiagnosticSignHint", { link = "DiagnosticFloatingHint" })
hi(0, "DiagnosticSignInfo", { link = "DiagnosticFloatingInfo" })
hi(0, "DiagnosticSignOk", { link = "DiagnosticFloatingOk" })
hi(0, "DiagnosticSignWarn", { link = "DiagnosticFloatingWarn" })
hi(0, "DiagnosticUnderlineError", { sp = "#a2191f", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#0043ce", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#005d5d", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#0e6027", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#6929c4", underline = true })
hi(0, "DiagnosticWarn", { ctermfg = 3, fg = "#6929c4" })
hi(0, "DiffAdd", { bg = "#e0e0e0", ctermbg = 2, ctermfg = 15, fg = "#0e6027" })
hi(0, "DiffChange", { bg = "#e0e0e0", fg = "#6929c4" })
hi(0, "DiffDelete", { bg = "#e0e0e0", ctermfg = 1, fg = "#a2191f" })
hi(0, "DiffText", { bg = "#e0e0e0", ctermbg = 6, ctermfg = 15, fg = "#0043ce" })
hi(0, "Directory", { ctermfg = 6, fg = "#0043ce" })
hi(0, "EndOfBuffer", { fg = "#6f6f6f" })
hi(0, "Error", { bg = "#a2191f", ctermbg = 1, ctermfg = 15, fg = "#f4f4f4" })
hi(0, "ErrorMsg", { bg = "#f4f4f4", ctermfg = 1, fg = "#a2191f" })
hi(0, "Exception", { fg = "#a2191f" })
hi(0, "FinderParam", { fg = "#a2191f" })
hi(0, "FinderSpinner", { fg = "#0e6027" })
hi(0, "FinderSpinnerBorder", { fg = "#9f1853" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#ba4e00" })
hi(0, "Float", { fg = "#ba4e00" })
hi(0, "FoldColumn", { bg = "#e0e0e0", fg = "#005d5d" })
hi(0, "Folded", { bg = "#e0e0e0", fg = "#6f6f6f" })
hi(0, "Function", { ctermfg = 6, fg = "#0043ce" })
hi(0, "GitSignsAdd", { bg = "#e0e0e0", fg = "#0e6027" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { bg = "#e0e0e0", fg = "#6929c4" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { bg = "#e0e0e0", fg = "#a2191f" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsUntracked", { bg = "#e0e0e0", fg = "#0043ce" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HopNextKey", { bold = true, fg = "#6929c4", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#a2191f", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#393939", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#ba4e00", nocombine = true })
hi(0, "HopUnmatched", { link = "Comment" })
hi(0, "HydraAmaranth", { fg = "#6929c4" })
hi(0, "HydraBlue", { fg = "#0043ce" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#ba4e00" })
hi(0, "HydraRed", { fg = "#a2191f" })
hi(0, "HydraTeal", { fg = "#0e6027" })
hi(0, "Identifier", { fg = "#0043ce" })
hi(0, "Ignore", { fg = "#005d5d" })
hi(0, "IncSearch", { bg = "#ba4e00", fg = "#e0e0e0" })
hi(0, "Include", { fg = "#0043ce" })
hi(0, "IndentBlanklineChar", { fg = "#c6c6c6", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#9f1853", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#9f1853", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#a2191f", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#ba4e00", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#684e00", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#0e6027", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#005d5d", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#0043ce", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#6929c4", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#9f1853", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#6929c4" })
hi(0, "LSOutlinePreviewBorder", { fg = "#9f1853" })
hi(0, "Label", { fg = "#684e00" })
hi(0, "LazyButton", { bg = "#e0e0e0" })
hi(0, "LazyButtonActive", { bg = "#c6c6c6" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyH1", { bg = "#c6c6c6", bold = true })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabel", { bold = true, fg = "#a2191f", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#ba4e00", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#6929c4", nocombine = true, underline = true })
hi(0, "LightspeedCursor", { link = "Cursor" })
hi(0, "LightspeedGreyWash", { link = "Comment" })
hi(0, "LightspeedLabel", { bold = true, fg = "#6929c4", underline = true })
hi(0, "LightspeedLabelDistant", { bold = true, fg = "#0043ce", underline = true })
hi(0, "LightspeedMaskedChar", { fg = "#393939" })
hi(0, "LightspeedOneCharMatch", { link = "LightspeedShortcut" })
hi(0, "LightspeedPendingOpArea", { link = "IncSearch" })
hi(0, "LightspeedShortcut", { bold = true, fg = "#161616" })
hi(0, "LightspeedUniqueChar", { link = "LightspeedUnlabeledMatch" })
hi(0, "LightspeedUnlabeledMatch", { bold = true, fg = "#161616" })
hi(0, "LineNr", { bg = "#e0e0e0", fg = "#6f6f6f" })
hi(0, "LineNrAbove", { bg = "#e0e0e0", fg = "#6f6f6f" })
hi(0, "LineNrBelow", { bg = "#e0e0e0", fg = "#6f6f6f" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspReferenceText", { bg = "#c6c6c6" })
hi(0, "LspSagaAutoPreview", { fg = "#9f1853" })
hi(0, "LspSagaBorderTitle", { link = "Title" })
hi(0, "LspSagaCodeActionBorder", { fg = "#9f1853" })
hi(0, "LspSagaCodeActionContent", { fg = "#161616" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#0043ce" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#9f1853" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#9f1853" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#6929c4" })
hi(0, "LspSagaFinderSelection", { fg = "#684e00" })
hi(0, "LspSagaHoverBorder", { fg = "#9f1853" })
hi(0, "LspSagaLspFinderBorder", { fg = "#9f1853" })
hi(0, "LspSagaRenameBorder", { fg = "#9f1853" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#9f1853" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "Macro", { fg = "#a2191f" })
hi(0, "MasonError", { fg = "#a2191f" })
hi(0, "MasonHeader", { bg = "#0043ce", bold = true, fg = "#f4f4f4" })
hi(0, "MasonHeaderSecondary", { bg = "#9f1853", bold = true, fg = "#f4f4f4" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#9f1853" })
hi(0, "MasonHighlightBlock", { bg = "#9f1853", fg = "#f4f4f4" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#0043ce", fg = "#f4f4f4" })
hi(0, "MasonHighlightSecondary", { fg = "#0043ce" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#6f6f6f", fg = "#f4f4f4" })
hi(0, "MasonMutedBlockBold", { bg = "#6f6f6f", bold = true, fg = "#f4f4f4" })
hi(0, "MatchParen", { bg = "#c6c6c6" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "NormalFloat" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { bg = "#e0e0e0", bold = true, fg = "#0043ce" })
hi(0, "MiniCompletionActiveParameter", { bg = "#c6c6c6" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hi(0, "MiniDiffOverChange", { link = "DiffText" })
hi(0, "MiniDiffOverContext", { link = "DiffChange" })
hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
hi(0, "MiniDiffSignAdd", { bg = "#e0e0e0", fg = "#0e6027" })
hi(0, "MiniDiffSignChange", { bg = "#e0e0e0", fg = "#6929c4" })
hi(0, "MiniDiffSignDelete", { bg = "#e0e0e0", fg = "#a2191f" })
hi(0, "MiniFilesBorder", { link = "NormalFloat" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { bg = "#c6c6c6" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#161616" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { bg = "#e0e0e0", fg = "#0043ce" })
hi(0, "MiniFilesTitleFocused", { bg = "#e0e0e0", bold = true, fg = "#0043ce" })
hi(0, "MiniHipatternsFixme", { bg = "#a2191f", bold = true, fg = "#f4f4f4" })
hi(0, "MiniHipatternsHack", { bg = "#6929c4", bold = true, fg = "#f4f4f4" })
hi(0, "MiniHipatternsNote", { bg = "#0043ce", bold = true, fg = "#f4f4f4" })
hi(0, "MiniHipatternsTodo", { bg = "#005d5d", bold = true, fg = "#f4f4f4" })
hi(0, "MiniIconsAzure", { fg = "#0043ce" })
hi(0, "MiniIconsBlue", { fg = "#9f1853" })
hi(0, "MiniIconsCyan", { fg = "#005d5d" })
hi(0, "MiniIconsGreen", { fg = "#0e6027" })
hi(0, "MiniIconsGrey", { fg = "#161616" })
hi(0, "MiniIconsOrange", { fg = "#ba4e00" })
hi(0, "MiniIconsPurple", { fg = "#6929c4" })
hi(0, "MiniIconsRed", { fg = "#a2191f" })
hi(0, "MiniIconsYellow", { fg = "#684e00" })
hi(0, "MiniIndentscopeSymbol", { fg = "#9f1853" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#a2191f" })
hi(0, "MiniJump", { link = "SpellRare" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bg = "#e0e0e0", bold = true, fg = "#161616", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#f4f4f4", fg = "#262626", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#e0e0e0", fg = "#161616" })
hi(0, "MiniMapSymbolCount", { fg = "#005d5d" })
hi(0, "MiniMapSymbolLine", { fg = "#0043ce" })
hi(0, "MiniMapSymbolView", { fg = "#9f1853" })
hi(0, "MiniNotifyBorder", { link = "NormalFloat" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "NormalFloat" })
hi(0, "MiniPickBorderBusy", { bg = "#e0e0e0", fg = "#6929c4" })
hi(0, "MiniPickBorderText", { bg = "#e0e0e0", bold = true, fg = "#0043ce" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { fg = "#161616" })
hi(0, "MiniPickMatchCurrent", { bg = "#c6c6c6" })
hi(0, "MiniPickMatchMarked", { bg = "#6f6f6f" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { bg = "#c6c6c6" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { bg = "#e0e0e0", fg = "#0e6027" })
hi(0, "MiniStarterCurrent", {})
hi(0, "MiniStarterFooter", { fg = "#0043ce" })
hi(0, "MiniStarterHeader", { fg = "#0043ce" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { fg = "#161616" })
hi(0, "MiniStarterItemBullet", { fg = "#9f1853" })
hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#a2191f" })
hi(0, "MiniStarterQuery", { bold = true, fg = "#0e6027" })
hi(0, "MiniStarterSection", { fg = "#9f1853" })
hi(0, "MiniStatuslineDevinfo", { bg = "#c6c6c6", fg = "#393939" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#e0e0e0", fg = "#6f6f6f" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(0, "MiniStatuslineModeCommand", { bg = "#a2191f", bold = true, fg = "#f4f4f4" })
hi(0, "MiniStatuslineModeInsert", { bg = "#0043ce", bold = true, fg = "#f4f4f4" })
hi(0, "MiniStatuslineModeNormal", { bg = "#161616", bold = true, fg = "#f4f4f4" })
hi(0, "MiniStatuslineModeOther", { bg = "#6f6f6f", bold = true, fg = "#f4f4f4" })
hi(0, "MiniStatuslineModeReplace", { bg = "#6929c4", bold = true, fg = "#f4f4f4" })
hi(0, "MiniStatuslineModeVisual", { bg = "#0e6027", bold = true, fg = "#f4f4f4" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#c6c6c6", bold = true, fg = "#161616" })
hi(0, "MiniTablineHidden", { bg = "#e0e0e0", fg = "#393939" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#161616", bold = true, fg = "#c6c6c6" })
hi(0, "MiniTablineModifiedHidden", { bg = "#393939", fg = "#e0e0e0" })
hi(0, "MiniTablineModifiedVisible", { bg = "#393939", bold = true, fg = "#c6c6c6" })
hi(0, "MiniTablineTabpagesection", { bg = "#684e00", bold = true, fg = "#e0e0e0" })
hi(0, "MiniTablineVisible", { bg = "#e0e0e0", bold = true, fg = "#161616" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#a2191f" })
hi(0, "MiniTestPass", { bold = true, fg = "#0e6027" })
hi(0, "MiniTrailspace", { link = "Error" })
hi(0, "ModeMsg", { ctermfg = 2, fg = "#0e6027" })
hi(0, "MoreMsg", { ctermfg = 6, fg = "#0e6027" })
hi(0, "MsgArea", { bg = "#f4f4f4", fg = "#161616" })
hi(0, "MsgSeparator", { bg = "#c6c6c6", fg = "#393939" })
hi(0, "NeoTreeDimText", { fg = "#6f6f6f" })
hi(0, "NeoTreeDotfile", { fg = "#393939" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#c6c6c6" })
hi(0, "NeoTreeGitAdded", { fg = "#0e6027" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#a2191f" })
hi(0, "NeoTreeGitDeleted", { fg = "#a2191f" })
hi(0, "NeoTreeGitModified", { fg = "#6929c4" })
hi(0, "NeoTreeGitUnstaged", { fg = "#a2191f" })
hi(0, "NeoTreeGitUntracked", { fg = "#684e00" })
hi(0, "NeoTreeMessage", { bg = "#e0e0e0", fg = "#161616" })
hi(0, "NeoTreeModified", { fg = "#161616" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#0043ce" })
hi(0, "NeoTreeTabInactive", { fg = "#393939" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#c6c6c6", fg = "#6f6f6f" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#e0e0e0", fg = "#e0e0e0" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { fg = "#0043ce" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#0043ce" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#0043ce" })
hi(0, "NoiceConfirmBorder", { fg = "#6929c4" })
hi(0, "NonText", { fg = "#6f6f6f" })
hi(0, "Normal", { fg = "#161616" })
hi(0, "NormalFloat", { bg = "#e0e0e0", fg = "#161616" })
hi(0, "NormalNC", { bg = "#f4f4f4", fg = "#161616" })
hi(0, "NotifyDEBUGBorder", { fg = "#6f6f6f" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { fg = "#a2191f" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { fg = "#005d5d" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#0043ce" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#6929c4" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "Number", { fg = "#ba4e00" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#0e6027" })
hi(0, "NvimTreeFolderIcon", { fg = "#6f6f6f" })
hi(0, "NvimTreeGitDeleted", { fg = "#a2191f" })
hi(0, "NvimTreeGitDirty", { fg = "#a2191f" })
hi(0, "NvimTreeGitMerge", { fg = "#005d5d" })
hi(0, "NvimTreeGitNew", { fg = "#684e00" })
hi(0, "NvimTreeGitRenamed", { fg = "#6929c4" })
hi(0, "NvimTreeGitStaged", { fg = "#0e6027" })
hi(0, "NvimTreeImageFile", { bold = true, fg = "#6929c4" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { link = "NvimTreeGitRenamed" })
hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#0043ce", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#9f1853" })
hi(0, "NvimTreeWindowPicker", { bg = "#e0e0e0", bold = true, fg = "#161616" })
hi(0, "Operator", { fg = "#161616" })
hi(0, "OutlineDetail", { fg = "#6f6f6f" })
hi(0, "OutlineFoldPrefix", { fg = "#a2191f" })
hi(0, "OutlineIndentEvn", { fg = "#393939" })
hi(0, "OutlineIndentOdd", { fg = "#161616" })
hi(0, "Pmenu", { bg = "#e0e0e0", fg = "#161616" })
hi(0, "PmenuSbar", { bg = "#c6c6c6" })
hi(0, "PmenuSel", { bg = "#161616", fg = "#e0e0e0" })
hi(0, "PmenuThumb", { bg = "#161616" })
hi(0, "PounceAccept", { bg = "#a2191f", bold = true, fg = "#f4f4f4", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#0e6027", bold = true, fg = "#f4f4f4", nocombine = true })
hi(0, "PounceGap", { bg = "#6f6f6f", bold = true, fg = "#f4f4f4", nocombine = true })
hi(0, "PounceMatch", { bg = "#161616", bold = true, fg = "#f4f4f4", nocombine = true })
hi(0, "PreCondit", { fg = "#684e00" })
hi(0, "PreProc", { fg = "#684e00" })
hi(0, "Question", { ctermfg = 6, fg = "#0043ce" })
hi(0, "QuickFixLine", { bg = "#e0e0e0", ctermfg = 6 })
hi(0, "RainbowDelimiterBlue", { fg = "#0043ce" })
hi(0, "RainbowDelimiterCyan", { fg = "#005d5d" })
hi(0, "RainbowDelimiterGreen", { fg = "#0e6027" })
hi(0, "RainbowDelimiterOrange", { fg = "#ba4e00" })
hi(0, "RainbowDelimiterRed", { fg = "#a2191f" })
hi(0, "RainbowDelimiterViolet", { fg = "#6929c4" })
hi(0, "RainbowDelimiterYellow", { fg = "#684e00" })
hi(0, "References", { fg = "#0e6027" })
hi(0, "ReferencesIcon", { fg = "#0043ce" })
hi(0, "Removed", { ctermfg = 1, fg = "#a2191f" })
hi(0, "Repeat", { fg = "#684e00" })
hi(0, "Search", { bg = "#684e00", ctermbg = 3, ctermfg = 15, fg = "#e0e0e0" })
hi(0, "SignColumn", { bg = "#e0e0e0", fg = "#6f6f6f" })
hi(0, "Sneak", { bg = "#6929c4", fg = "#f4f4f4" })
hi(0, "SneakLabel", { bg = "#6929c4", bold = true, fg = "#f4f4f4" })
hi(0, "SneakScope", { bg = "#161616", fg = "#f4f4f4" })
hi(0, "Special", { ctermfg = 6, fg = "#005d5d" })
hi(0, "SpecialChar", { fg = "#9f1853" })
hi(0, "SpecialComment", { fg = "#005d5d" })
hi(0, "SpecialKey", { fg = "#6f6f6f" })
hi(0, "SpellBad", { sp = "#a2191f", undercurl = true })
hi(0, "SpellCap", { sp = "#0043ce", undercurl = true })
hi(0, "SpellLocal", { sp = "#005d5d", undercurl = true })
hi(0, "SpellRare", { sp = "#6929c4", undercurl = true })
hi(0, "Statement", { fg = "#a2191f" })
hi(0, "StatusLine", { bg = "#c6c6c6", fg = "#393939" })
hi(0, "StatusLineNC", { bg = "#e0e0e0", fg = "#6f6f6f" })
hi(0, "StorageClass", { fg = "#684e00" })
hi(0, "String", { ctermfg = 2, fg = "#0e6027" })
hi(0, "Structure", { fg = "#6929c4" })
hi(0, "Substitute", { bg = "#684e00", fg = "#e0e0e0" })
hi(0, "TabLine", { bg = "#e0e0e0", fg = "#6f6f6f" })
hi(0, "TabLineFill", { bg = "#e0e0e0", fg = "#6f6f6f" })
hi(0, "TabLineSel", { bg = "#e0e0e0", fg = "#0e6027" })
hi(0, "Tag", { fg = "#684e00" })
hi(0, "TargetFileName", { fg = "#161616" })
hi(0, "TelescopeBorder", { fg = "#9f1853" })
hi(0, "TelescopeMatching", { fg = "#684e00" })
hi(0, "TelescopeMultiSelection", { bg = "#e0e0e0", bold = true })
hi(0, "TelescopeSelection", { bg = "#e0e0e0", bold = true })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "Title", { fg = "#0043ce" })
hi(0, "Todo", { bg = "#e0e0e0", fg = "#684e00" })
hi(0, "TooLong", { fg = "#a2191f" })
hi(0, "TroubleCount", { bold = true, fg = "#0e6027" })
hi(0, "TroubleFoldIcon", { fg = "#161616" })
hi(0, "TroubleIndent", { fg = "#c6c6c6" })
hi(0, "TroubleLocation", { fg = "#393939" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { fg = "#161616" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { fg = "#684e00" })
hi(0, "Typedef", { fg = "#684e00" })
hi(0, "VertSplit", { bg = "#c6c6c6", fg = "#c6c6c6" })
hi(0, "Visual", { bg = "#a6c8ff" })
hi(0, "VisualNOS", { fg = "#a2191f" })
hi(0, "WarningMsg", { ctermfg = 3, fg = "#a2191f" })
hi(0, "WhichKey", { fg = "#0043ce" })
hi(0, "WhichKeyDesc", { fg = "#161616" })
hi(0, "WhichKeyFloat", { bg = "#e0e0e0", fg = "#161616" })
hi(0, "WhichKeyGroup", { fg = "#6929c4" })
hi(0, "WhichKeySeparator", { bg = "#e0e0e0", fg = "#0e6027" })
hi(0, "WhichKeyValue", { fg = "#6f6f6f" })
hi(0, "Whitespace", { fg = "#6f6f6f" })
hi(0, "WildMenu", { bg = "#684e00", fg = "#a2191f" })
hi(0, "WinBar", { bg = "#c6c6c6", fg = "#393939" })
hi(0, "WinBarNC", { bg = "#e0e0e0", fg = "#6f6f6f" })
hi(0, "WinSeparator", { bg = "#c6c6c6", fg = "#c6c6c6" })
hi(0, "diffAdded", { fg = "#0e6027" })
hi(0, "diffChanged", { fg = "#6929c4" })
hi(0, "diffFile", { fg = "#ba4e00" })
hi(0, "diffLine", { fg = "#005d5d" })
hi(0, "diffRemoved", { fg = "#a2191f" })
hi(0, "gitcommitBranch", { bold = true, fg = "#ba4e00" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#a2191f" })
hi(0, "gitcommitDiscardedType", { fg = "#0043ce" })
hi(0, "gitcommitHeader", { fg = "#6929c4" })
hi(0, "gitcommitOverflow", { fg = "#a2191f" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#0e6027" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#0e6027" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#684e00" })
hi(0, "lCursor", { bg = "#161616", fg = "#f4f4f4" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#f4f4f4"
g.terminal_color_1 = "#a2191f"
g.terminal_color_2 = "#0e6027"
g.terminal_color_3 = "#684e00"
g.terminal_color_4 = "#0043ce"
g.terminal_color_5 = "#6929c4"
g.terminal_color_6 = "#005d5d"
g.terminal_color_7 = "#161616"
g.terminal_color_8 = "#6f6f6f"
g.terminal_color_9 = "#a2191f"
g.terminal_color_10 = "#0e6027"
g.terminal_color_11 = "#684e00"
g.terminal_color_12 = "#0043ce"
g.terminal_color_13 = "#6929c4"
g.terminal_color_14 = "#005d5d"
g.terminal_color_15 = "#161616"
