-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
  vim.cmd 'highlight clear'
end
vim.g.colors_name = 'solarized_hushed_dark'

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, '@keyword.return', { fg = '#839496' })
hi(0, '@lsp.mod.defaultLibrary', { link = 'Special' })
hi(0, '@lsp.mod.deprecated', { fg = '#dc322f' })
hi(0, '@lsp.type.variable', { fg = '#93a1a1' })
hi(0, '@markup.strikethrough', {})
hi(0, '@markup.underline', {})
hi(0, '@symbol', { fg = '#6c71c4' })
hi(0, '@text.emphasis', { italic = true })
hi(0, '@text.strike', { strikethrough = true })
hi(0, '@text.strong', { bold = true })
hi(0, '@variable', { fg = '#93a1a1' })
hi(0, 'Added', { ctermfg = 10, fg = '#859900' })
hi(0, 'Beacon', { bg = '#fdf6e3' })
hi(0, 'Bold', { bold = true })
hi(0, 'Boolean', { fg = '#839496' })
hi(0, 'BufferCurrent', { bg = '#586e75', bold = true, fg = '#93a1a1' })
hi(0, 'BufferCurrentIcon', { bg = '#586e75' })
hi(0, 'BufferCurrentIndex', { link = 'BufferCurrentIcon' })
hi(0, 'BufferCurrentMod', { bg = '#586e75', bold = true, fg = '#dc322f' })
hi(0, 'BufferCurrentSign', { link = 'BufferCurrent' })
hi(0, 'BufferCurrentTarget', { bg = '#586e75', bold = true, fg = '#6c71c4' })
hi(0, 'BufferInactive', { bg = '#073642', fg = '#839496' })
hi(0, 'BufferInactiveIcon', { bg = '#073642' })
hi(0, 'BufferInactiveIndex', { link = 'BufferInactiveIcon' })
hi(0, 'BufferInactiveMod', { bg = '#073642', fg = '#dc322f' })
hi(0, 'BufferInactiveSign', { link = 'BufferInactive' })
hi(0, 'BufferInactiveTarget', { bg = '#073642', bold = true, fg = '#6c71c4' })
hi(0, 'BufferLineBuffer', { fg = '#839496' })
hi(0, 'BufferLineBufferSelected', { bold = true, fg = '#93a1a1' })
hi(0, 'BufferLineBufferVisible', { fg = '#93a1a1' })
hi(0, 'BufferLineCloseButton', { link = 'BufferLineBackground' })
hi(0, 'BufferLineCloseButtonSelected', { link = 'BufferLineBufferSelected' })
hi(0, 'BufferLineCloseButtonVisible', { link = 'BufferLineBufferVisible' })
hi(0, 'BufferLineFill', { link = 'Normal' })
hi(0, 'BufferLineTab', { bg = '#b58900', fg = '#002b36' })
hi(0, 'BufferLineTabSelected', { bg = '#b58900', bold = true, fg = '#002b36' })
hi(0, 'BufferOffset', { link = 'Normal' })
hi(0, 'BufferTabpageFill', { link = 'Normal' })
hi(0, 'BufferTabpages', { bg = '#b58900', bold = true, fg = '#073642' })
hi(0, 'BufferVisible', { bg = '#073642', bold = true, fg = '#93a1a1' })
hi(0, 'BufferVisibleIcon', { bg = '#073642' })
hi(0, 'BufferVisibleIndex', { link = 'BufferVisibleIcon' })
hi(0, 'BufferVisibleMod', { bg = '#073642', bold = true, fg = '#dc322f' })
hi(0, 'BufferVisibleSign', { link = 'BufferVisible' })
hi(0, 'BufferVisibleTarget', { bg = '#073642', bold = true, fg = '#6c71c4' })
hi(0, 'Changed', { ctermfg = 14, fg = '#6c71c4' })
hi(0, 'Character', { fg = '#dc322f' })
hi(0, 'CmpItemAbbr', { fg = '#93a1a1' })
hi(0, 'CmpItemAbbrDeprecated', { fg = '#657b83' })
hi(0, 'CmpItemAbbrMatch', { bold = true, fg = '#b58900' })
hi(0, 'CmpItemAbbrMatchFuzzy', { bold = true, fg = '#b58900' })
hi(0, 'CmpItemKind', { bg = '#073642', fg = '#d33682' })
hi(0, 'CmpItemKindClass', { link = 'Type' })
hi(0, 'CmpItemKindColor', { link = 'Special' })
hi(0, 'CmpItemKindConstant', { link = 'Constant' })
hi(0, 'CmpItemKindConstructor', { link = 'Type' })
hi(0, 'CmpItemKindEnum', { link = 'Structure' })
hi(0, 'CmpItemKindEnumMember', { link = 'Structure' })
hi(0, 'CmpItemKindEvent', { link = 'Exception' })
hi(0, 'CmpItemKindField', { link = 'Structure' })
hi(0, 'CmpItemKindFile', { link = 'Tag' })
hi(0, 'CmpItemKindFolder', { link = 'Directory' })
hi(0, 'CmpItemKindFunction', { link = 'Function' })
hi(0, 'CmpItemKindInterface', { link = 'Structure' })
hi(0, 'CmpItemKindKeyword', { link = 'Keyword' })
hi(0, 'CmpItemKindMethod', { link = 'Function' })
hi(0, 'CmpItemKindModule', { link = 'Structure' })
hi(0, 'CmpItemKindOperator', { link = 'Operator' })
hi(0, 'CmpItemKindProperty', { link = 'Structure' })
hi(0, 'CmpItemKindReference', { link = 'Tag' })
hi(0, 'CmpItemKindSnippet', { link = 'Special' })
hi(0, 'CmpItemKindStruct', { link = 'Structure' })
hi(0, 'CmpItemKindText', { link = 'Statement' })
hi(0, 'CmpItemKindTypeParameter', { link = 'Type' })
hi(0, 'CmpItemKindUnit', { link = 'Special' })
hi(0, 'CmpItemKindValue', { link = 'Identifier' })
hi(0, 'CmpItemKindVariable', { link = 'Delimiter' })
hi(0, 'CmpItemMenu', { bg = '#073642', fg = '#93a1a1' })
hi(0, 'CocCodeLens', { link = 'LspCodeLens' })
hi(0, 'CocDisabled', { link = 'Comment' })
hi(0, 'CocFadeOut', { link = 'Comment' })
hi(0, 'CocMarkdownLink', { fg = '#d33682' })
hi(0, 'CocMenuSel', { bg = '#586e75' })
hi(0, 'CocNotificationProgress', { link = 'CocMarkdownLink' })
hi(0, 'CocPumVirtualText', { link = 'CocMarkdownLink' })
hi(0, 'CocSearch', { fg = '#b58900' })
hi(0, 'CocSelectedText', { fg = '#dc322f' })
hi(0, 'ColorColumn', { bg = '#073642' })
hi(0, 'Comment', { fg = '#657b83' })
hi(0, 'Conceal', { fg = '#268bd2' })
hi(0, 'Conditional', { fg = '#6c71c4' })
hi(0, 'Constant', { fg = '#839496' })
hi(0, 'CurSearch', { bg = '#cb4b16', ctermbg = 11, ctermfg = 0, fg = '#073642' })
hi(0, 'Cursor', { bg = '#93a1a1', fg = '#002b36' })
hi(0, 'CursorColumn', { bg = '#073642' })
hi(0, 'CursorIM', { bg = '#93a1a1', fg = '#002b36' })
hi(0, 'CursorLine', { bg = '#073642' })
hi(0, 'CursorLineFold', { bg = '#073642', fg = '#2aa198' })
hi(0, 'CursorLineNr', { bg = '#073642', fg = '#839496' })
hi(0, 'CursorLineSign', { bg = '#073642', fg = '#657b83' })
hi(0, 'DapUIBreakpointsCurrentLine', { bold = true, fg = '#859900' })
hi(0, 'DapUIBreakpointsDisabledLine', { link = 'Comment' })
hi(0, 'DapUIBreakpointsInfo', { link = 'DiagnosticInfo' })
hi(0, 'DapUIBreakpointsPath', { link = 'Directory' })
hi(0, 'DapUIDecoration', { link = 'Title' })
hi(0, 'DapUIFloatBorder', { link = 'SpecialChar' })
hi(0, 'DapUILineNumber', { link = 'Title' })
hi(0, 'DapUIModifiedValue', { bold = true, fg = '#6c71c4' })
hi(0, 'DapUIScope', { link = 'Title' })
hi(0, 'DapUISource', { link = 'Directory' })
hi(0, 'DapUIStoppedThread', { link = 'Title' })
hi(0, 'DapUIThread', { link = 'String' })
hi(0, 'DapUIType', { link = 'Type' })
hi(0, 'DapUIWatchesEmpty', { link = 'ErrorMsg' })
hi(0, 'DapUIWatchesError', { link = 'DiagnosticError' })
hi(0, 'DapUIWatchesValue', { link = 'String' })
hi(0, 'DashboardCenter', { link = 'Delimiter' })
hi(0, 'DashboardFooter', { link = 'Title' })
hi(0, 'DashboardHeader', { link = 'Title' })
hi(0, 'DashboardShortCut', { link = 'WarningMsg' })
hi(0, 'Debug', { fg = '#dc322f' })
hi(0, 'Define', { fg = '#6c71c4' })
hi(0, 'Definitions', { fg = '#859900' })
hi(0, 'DefinitionsIcon', { fg = '#268bd2' })
hi(0, 'Delimiter', { fg = '#839496' })
hi(0, 'DiagnosticError', { ctermfg = 9, fg = '#dc322f' })
hi(0, 'DiagnosticFloatingError', { bg = '#073642', fg = '#dc322f' })
hi(0, 'DiagnosticFloatingHint', { bg = '#073642', fg = '#268bd2' })
hi(0, 'DiagnosticFloatingInfo', { bg = '#073642', fg = '#2aa198' })
hi(0, 'DiagnosticFloatingOk', { bg = '#073642', fg = '#859900' })
hi(0, 'DiagnosticFloatingWarn', { bg = '#073642', fg = '#6c71c4' })
hi(0, 'DiagnosticHint', { ctermfg = 12, fg = '#268bd2' })
hi(0, 'DiagnosticInfo', { ctermfg = 14, fg = '#2aa198' })
hi(0, 'DiagnosticOk', { ctermfg = 10, fg = '#859900' })
hi(0, 'DiagnosticSignError', { link = 'DiagnosticFloatingError' })
hi(0, 'DiagnosticSignHint', { link = 'DiagnosticFloatingHint' })
hi(0, 'DiagnosticSignInfo', { link = 'DiagnosticFloatingInfo' })
hi(0, 'DiagnosticSignOk', { link = 'DiagnosticFloatingOk' })
hi(0, 'DiagnosticSignWarn', { link = 'DiagnosticFloatingWarn' })
hi(0, 'DiagnosticUnderlineError', { sp = '#dc322f', underline = true })
hi(0, 'DiagnosticUnderlineHint', { sp = '#268bd2', underline = true })
hi(0, 'DiagnosticUnderlineInfo', { sp = '#2aa198', underline = true })
hi(0, 'DiagnosticUnderlineOk', { sp = '#859900', underline = true })
hi(0, 'DiagnosticUnderlineWarn', { sp = '#6c71c4', underline = true })
hi(0, 'DiagnosticWarn', { ctermfg = 11, fg = '#6c71c4' })
hi(0, 'DiffAdd', { bg = '#073642', ctermbg = 10, ctermfg = 0, fg = '#859900' })
hi(0, 'DiffChange', { bg = '#073642', fg = '#6c71c4' })
hi(0, 'DiffDelete', { bg = '#073642', ctermfg = 9, fg = '#dc322f' })
hi(0, 'DiffText', { bg = '#073642', ctermbg = 14, ctermfg = 0, fg = '#268bd2' })
hi(0, 'Directory', { ctermfg = 14, fg = '#268bd2' })
hi(0, 'EndOfBuffer', { fg = '#657b83' })
hi(0, 'Error', { bg = '#dc322f', ctermbg = 9, ctermfg = 0, fg = '#002b36' })
hi(0, 'ErrorMsg', { bg = '#002b36', ctermfg = 9, fg = '#dc322f' })
hi(0, 'Exception', { fg = '#dc322f' })
hi(0, 'FinderParam', { fg = '#dc322f' })
hi(0, 'FinderSpinner', { fg = '#859900' })
hi(0, 'FinderSpinnerBorder', { fg = '#d33682' })
hi(0, 'FinderSpinnerTitle', { link = 'Title' })
hi(0, 'FinderVirtText', { fg = '#cb4b16' })
hi(0, 'Float', { fg = '#cb4b16' })
hi(0, 'FoldColumn', { bg = '#073642', fg = '#2aa198' })
hi(0, 'Folded', { bg = '#073642', fg = '#657b83' })
hi(0, 'Function', { fg = '#839496' })
hi(0, 'GitSignsAdd', { bg = '#073642', fg = '#859900' })
hi(0, 'GitSignsAddInline', { link = 'GitSignsAdd' })
hi(0, 'GitSignsAddLn', { link = 'GitSignsAdd' })
hi(0, 'GitSignsChange', { bg = '#073642', fg = '#6c71c4' })
hi(0, 'GitSignsChangeInline', { link = 'GitSignsChange' })
hi(0, 'GitSignsChangeLn', { link = 'GitSignsChange' })
hi(0, 'GitSignsDelete', { bg = '#073642', fg = '#dc322f' })
hi(0, 'GitSignsDeleteInline', { link = 'GitSignsDelete' })
hi(0, 'GitSignsDeleteLn', { link = 'GitSignsDelete' })
hi(0, 'GitSignsUntracked', { bg = '#073642', fg = '#268bd2' })
hi(0, 'GitSignsUntrackedInline', { link = 'GitSignsUntracked' })
hi(0, 'GitSignsUntrackedLn', { link = 'GitSignsUntracked' })
hi(0, 'HopNextKey', { bold = true, fg = '#6c71c4', nocombine = true })
hi(0, 'HopNextKey1', { bold = true, fg = '#dc322f', nocombine = true })
hi(0, 'HopNextKey2', { bold = true, fg = '#839496', nocombine = true })
hi(0, 'HopPreview', { bold = true, fg = '#cb4b16', nocombine = true })
hi(0, 'HopUnmatched', { link = 'Comment' })
hi(0, 'HydraAmaranth', { fg = '#6c71c4' })
hi(0, 'HydraBlue', { fg = '#268bd2' })
hi(0, 'HydraHint', { link = 'NormalFloat' })
hi(0, 'HydraPink', { fg = '#cb4b16' })
hi(0, 'HydraRed', { fg = '#dc322f' })
hi(0, 'HydraTeal', { fg = '#859900' })
hi(0, 'Identifier', { ctermfg = 12, fg = '#839496' })
hi(0, 'Ignore', { fg = '#2aa198' })
hi(0, 'IncSearch', { bg = '#cb4b16', fg = '#073642' })
hi(0, 'Include', { fg = '#268bd2' })
hi(0, 'IndentBlanklineChar', { fg = '#586e75', nocombine = true })
hi(0, 'IndentBlanklineContextChar', { fg = '#d33682', nocombine = true })
hi(0, 'IndentBlanklineContextStart', { nocombine = true, sp = '#d33682', underline = true })
hi(0, 'IndentBlanklineIndent1', { fg = '#dc322f', nocombine = true })
hi(0, 'IndentBlanklineIndent2', { fg = '#cb4b16', nocombine = true })
hi(0, 'IndentBlanklineIndent3', { fg = '#b58900', nocombine = true })
hi(0, 'IndentBlanklineIndent4', { fg = '#859900', nocombine = true })
hi(0, 'IndentBlanklineIndent5', { fg = '#2aa198', nocombine = true })
hi(0, 'IndentBlanklineIndent6', { fg = '#268bd2', nocombine = true })
hi(0, 'IndentBlanklineIndent7', { fg = '#6c71c4', nocombine = true })
hi(0, 'IndentBlanklineIndent8', { fg = '#d33682', nocombine = true })
hi(0, 'Italic', { italic = true })
hi(0, 'Keyword', { fg = '#839496' })
hi(0, 'LSOutlinePreviewBorder', { fg = '#d33682' })
hi(0, 'Label', { fg = '#b58900' })
hi(0, 'LazyButton', { bg = '#073642' })
hi(0, 'LazyButtonActive', { bg = '#586e75' })
hi(0, 'LazyDimmed', { link = 'Comment' })
hi(0, 'LazyH1', { bg = '#586e75', bold = true })
hi(0, 'LeapBackdrop', { link = 'Comment' })
hi(0, 'LeapLabelPrimary', { bold = true, fg = '#dc322f', nocombine = true })
hi(0, 'LeapLabelSecondary', { bold = true, fg = '#93a1a1', nocombine = true })
hi(0, 'LeapLabelSelected', { bold = true, fg = '#cb4b16', nocombine = true })
hi(0, 'LeapMatch', { bold = true, fg = '#6c71c4', nocombine = true, underline = true })
hi(0, 'LightspeedCursor', { link = 'Cursor' })
hi(0, 'LightspeedGreyWash', { link = 'Comment' })
hi(0, 'LightspeedLabel', { bold = true, fg = '#6c71c4', underline = true })
hi(0, 'LightspeedLabelDistant', { bold = true, fg = '#268bd2', underline = true })
hi(0, 'LightspeedMaskedChar', { fg = '#839496' })
hi(0, 'LightspeedOneCharMatch', { link = 'LightspeedShortcut' })
hi(0, 'LightspeedPendingOpArea', { link = 'IncSearch' })
hi(0, 'LightspeedShortcut', { bold = true, fg = '#fdf6e3' })
hi(0, 'LightspeedUniqueChar', { link = 'LightspeedUnlabeledMatch' })
hi(0, 'LightspeedUnlabeledMatch', { bold = true, fg = '#93a1a1' })
hi(0, 'LineNr', { bg = '#073642', fg = '#657b83' })
hi(0, 'LineNrAbove', { bg = '#073642', fg = '#657b83' })
hi(0, 'LineNrBelow', { bg = '#073642', fg = '#657b83' })
hi(0, 'LspCodeLens', { link = 'Comment' })
hi(0, 'LspCodeLensSeparator', { link = 'Comment' })
hi(0, 'LspReferenceText', { bg = '#586e75' })
hi(0, 'LspSagaAutoPreview', { fg = '#d33682' })
hi(0, 'LspSagaBorderTitle', { link = 'Title' })
hi(0, 'LspSagaCodeActionBorder', { fg = '#d33682' })
hi(0, 'LspSagaCodeActionContent', { fg = '#93a1a1' })
hi(0, 'LspSagaCodeActionTitle', { bold = true, fg = '#268bd2' })
hi(0, 'LspSagaDefPreviewBorder', { fg = '#d33682' })
hi(0, 'LspSagaDiagnosticBorder', { fg = '#d33682' })
hi(0, 'LspSagaDiagnosticHeader', { link = 'Title' })
hi(0, 'LspSagaDiagnosticSource', { fg = '#6c71c4' })
hi(0, 'LspSagaFinderSelection', { fg = '#b58900' })
hi(0, 'LspSagaHoverBorder', { fg = '#d33682' })
hi(0, 'LspSagaLspFinderBorder', { fg = '#d33682' })
hi(0, 'LspSagaRenameBorder', { fg = '#d33682' })
hi(0, 'LspSagaSignatureHelpBorder', { fg = '#d33682' })
hi(0, 'LspSignatureActiveParameter', { link = 'LspReferenceText' })
hi(0, 'Macro', { fg = '#dc322f' })
hi(0, 'MasonError', { fg = '#dc322f' })
hi(0, 'MasonHeader', { bg = '#268bd2', bold = true, fg = '#002b36' })
hi(0, 'MasonHeaderSecondary', { bg = '#d33682', bold = true, fg = '#002b36' })
hi(0, 'MasonHeading', { link = 'Bold' })
hi(0, 'MasonHighlight', { fg = '#d33682' })
hi(0, 'MasonHighlightBlock', { bg = '#d33682', fg = '#002b36' })
hi(0, 'MasonHighlightBlockBold', { link = 'MasonHeaderSecondary' })
hi(0, 'MasonHighlightBlockBoldSecondary', { link = 'MasonHeader' })
hi(0, 'MasonHighlightBlockSecondary', { bg = '#268bd2', fg = '#002b36' })
hi(0, 'MasonHighlightSecondary', { fg = '#268bd2' })
hi(0, 'MasonLink', { link = 'MasonHighlight' })
hi(0, 'MasonMuted', { link = 'Comment' })
hi(0, 'MasonMutedBlock', { bg = '#657b83', fg = '#002b36' })
hi(0, 'MasonMutedBlockBold', { bg = '#657b83', bold = true, fg = '#002b36' })
hi(0, 'MatchParen', { bg = '#586e75' })
hi(0, 'MiniAnimateCursor', { nocombine = true, reverse = true })
hi(0, 'MiniAnimateNormalFloat', { link = 'NormalFloat' })
hi(0, 'MiniClueBorder', { link = 'NormalFloat' })
hi(0, 'MiniClueDescGroup', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniClueDescSingle', { link = 'NormalFloat' })
hi(0, 'MiniClueNextKey', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniClueNextKeyWithPostkeys', { link = 'DiagnosticFloatingError' })
hi(0, 'MiniClueSeparator', { link = 'DiagnosticFloatingInfo' })
hi(0, 'MiniClueTitle', { bg = '#073642', bold = true, fg = '#268bd2' })
hi(0, 'MiniCompletionActiveParameter', { bg = '#586e75' })
hi(0, 'MiniCursorword', { underline = true })
hi(0, 'MiniCursorwordCurrent', { underline = true })
hi(0, 'MiniDepsChangeAdded', { link = 'diffAdded' })
hi(0, 'MiniDepsChangeRemoved', { link = 'diffRemoved' })
hi(0, 'MiniDepsHint', { link = 'DiagnosticHint' })
hi(0, 'MiniDepsInfo', { link = 'DiagnosticInfo' })
hi(0, 'MiniDepsPlaceholder', { link = 'Comment' })
hi(0, 'MiniDepsTitle', { link = 'Title' })
hi(0, 'MiniDepsTitleError', { link = 'DiffDelete' })
hi(0, 'MiniDepsTitleSame', { link = 'DiffText' })
hi(0, 'MiniDepsTitleUpdate', { link = 'DiffAdd' })
hi(0, 'MiniDiffOverAdd', { link = 'DiffAdd' })
hi(0, 'MiniDiffOverChange', { link = 'DiffText' })
hi(0, 'MiniDiffOverContext', { link = 'DiffChange' })
hi(0, 'MiniDiffOverDelete', { link = 'DiffDelete' })
hi(0, 'MiniDiffSignAdd', { bg = '#073642', fg = '#859900' })
hi(0, 'MiniDiffSignChange', { bg = '#073642', fg = '#6c71c4' })
hi(0, 'MiniDiffSignDelete', { bg = '#073642', fg = '#dc322f' })
hi(0, 'MiniFilesBorder', { link = 'NormalFloat' })
hi(0, 'MiniFilesBorderModified', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniFilesCursorLine', { bg = '#586e75' })
hi(0, 'MiniFilesDirectory', { link = 'Directory' })
hi(0, 'MiniFilesFile', { fg = '#93a1a1' })
hi(0, 'MiniFilesNormal', { link = 'NormalFloat' })
hi(0, 'MiniFilesTitle', { bg = '#073642', fg = '#268bd2' })
hi(0, 'MiniFilesTitleFocused', { bg = '#073642', bold = true, fg = '#268bd2' })
hi(0, 'MiniHipatternsFixme', { bg = '#dc322f', bold = true, fg = '#002b36' })
hi(0, 'MiniHipatternsHack', { bg = '#6c71c4', bold = true, fg = '#002b36' })
hi(0, 'MiniHipatternsNote', { bg = '#268bd2', bold = true, fg = '#002b36' })
hi(0, 'MiniHipatternsTodo', { bg = '#2aa198', bold = true, fg = '#002b36' })
hi(0, 'MiniIndentscopeSymbol', { fg = '#d33682' })
hi(0, 'MiniIndentscopeSymbolOff', { fg = '#dc322f' })
hi(0, 'MiniJump', { link = 'SpellRare' })
hi(0, 'MiniJump2dDim', { link = 'Comment' })
hi(0, 'MiniJump2dSpot', { bg = '#073642', bold = true, fg = '#fdf6e3', nocombine = true })
hi(0, 'MiniJump2dSpotAhead', { bg = '#002b36', fg = '#eee8d5', nocombine = true })
hi(0, 'MiniJump2dSpotUnique', { link = 'MiniJump2dSpot' })
hi(0, 'MiniMapNormal', { bg = '#073642', fg = '#93a1a1' })
hi(0, 'MiniMapSymbolCount', { fg = '#2aa198' })
hi(0, 'MiniMapSymbolLine', { fg = '#268bd2' })
hi(0, 'MiniMapSymbolView', { fg = '#d33682' })
hi(0, 'MiniNotifyBorder', { link = 'NormalFloat' })
hi(0, 'MiniNotifyNormal', { link = 'NormalFloat' })
hi(0, 'MiniNotifyTitle', { link = 'FloatTitle' })
hi(0, 'MiniOperatorsExchangeFrom', { link = 'IncSearch' })
hi(0, 'MiniPickBorder', { link = 'NormalFloat' })
hi(0, 'MiniPickBorderBusy', { bg = '#073642', fg = '#6c71c4' })
hi(0, 'MiniPickBorderText', { bg = '#073642', bold = true, fg = '#268bd2' })
hi(0, 'MiniPickHeader', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniPickIconDirectory', { link = 'Directory' })
hi(0, 'MiniPickIconFile', { fg = '#93a1a1' })
hi(0, 'MiniPickMatchCurrent', { bg = '#586e75' })
hi(0, 'MiniPickMatchMarked', { bg = '#657b83' })
hi(0, 'MiniPickMatchRanges', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniPickNormal', { link = 'NormalFloat' })
hi(0, 'MiniPickPreviewLine', { bg = '#586e75' })
hi(0, 'MiniPickPreviewRegion', { link = 'IncSearch' })
hi(0, 'MiniPickPrompt', { bg = '#073642', fg = '#859900' })
hi(0, 'MiniStarterFooter', { fg = '#268bd2' })
hi(0, 'MiniStarterHeader', { fg = '#268bd2' })
hi(0, 'MiniStarterInactive', { link = 'Comment' })
hi(0, 'MiniStarterItem', { fg = '#93a1a1' })
hi(0, 'MiniStarterItemBullet', { fg = '#d33682' })
hi(0, 'MiniStarterItemPrefix', { bold = true, fg = '#dc322f' })
hi(0, 'MiniStarterQuery', { bold = true, fg = '#859900' })
hi(0, 'MiniStarterSection', { fg = '#d33682' })
hi(0, 'MiniStatuslineDevinfo', { bg = '#586e75', fg = '#839496' })
hi(0, 'MiniStatuslineFileinfo', { link = 'MiniStatuslineDevinfo' })
hi(0, 'MiniStatuslineFilename', { bg = '#073642', fg = '#657b83' })
hi(0, 'MiniStatuslineInactive', { link = 'MiniStatuslineFilename' })
hi(0, 'MiniStatuslineModeCommand', { bg = '#dc322f', bold = true, fg = '#002b36' })
hi(0, 'MiniStatuslineModeInsert', { bg = '#268bd2', bold = true, fg = '#002b36' })
hi(0, 'MiniStatuslineModeNormal', { bg = '#93a1a1', bold = true, fg = '#002b36' })
hi(0, 'MiniStatuslineModeOther', { bg = '#657b83', bold = true, fg = '#002b36' })
hi(0, 'MiniStatuslineModeReplace', { bg = '#6c71c4', bold = true, fg = '#002b36' })
hi(0, 'MiniStatuslineModeVisual', { bg = '#859900', bold = true, fg = '#002b36' })
hi(0, 'MiniSurround', { link = 'IncSearch' })
hi(0, 'MiniTablineCurrent', { bg = '#586e75', bold = true, fg = '#93a1a1' })
hi(0, 'MiniTablineFill', {})
hi(0, 'MiniTablineHidden', { bg = '#073642', fg = '#839496' })
hi(0, 'MiniTablineModifiedCurrent', { bg = '#93a1a1', bold = true, fg = '#586e75' })
hi(0, 'MiniTablineModifiedHidden', { bg = '#839496', fg = '#073642' })
hi(0, 'MiniTablineModifiedVisible', { bg = '#839496', bold = true, fg = '#586e75' })
hi(0, 'MiniTablineTabpagesection', { bg = '#b58900', bold = true, fg = '#073642' })
hi(0, 'MiniTablineVisible', { bg = '#073642', bold = true, fg = '#93a1a1' })
hi(0, 'MiniTestEmphasis', { bold = true })
hi(0, 'MiniTestFail', { bold = true, fg = '#dc322f' })
hi(0, 'MiniTestPass', { bold = true, fg = '#859900' })
hi(0, 'MiniTrailspace', { link = 'Error' })
hi(0, 'ModeMsg', { ctermfg = 10, fg = '#859900' })
hi(0, 'MoreMsg', { ctermfg = 14, fg = '#859900' })
hi(0, 'MsgArea', { bg = '#002b36', fg = '#93a1a1' })
hi(0, 'MsgSeparator', { bg = '#586e75', fg = '#839496' })
hi(0, 'NeoTreeDimText', { fg = '#657b83' })
hi(0, 'NeoTreeDotfile', { fg = '#839496' })
hi(0, 'NeoTreeFadeText1', { link = 'NeoTreeDimText' })
hi(0, 'NeoTreeFadeText2', { fg = '#586e75' })
hi(0, 'NeoTreeGitAdded', { fg = '#859900' })
hi(0, 'NeoTreeGitConflict', { bold = true, fg = '#dc322f' })
hi(0, 'NeoTreeGitDeleted', { fg = '#dc322f' })
hi(0, 'NeoTreeGitModified', { fg = '#6c71c4' })
hi(0, 'NeoTreeGitUnstaged', { fg = '#dc322f' })
hi(0, 'NeoTreeGitUntracked', { fg = '#b58900' })
hi(0, 'NeoTreeMessage', { bg = '#073642', fg = '#93a1a1' })
hi(0, 'NeoTreeModified', { fg = '#fdf6e3' })
hi(0, 'NeoTreeRootName', { bold = true, fg = '#268bd2' })
hi(0, 'NeoTreeTabInactive', { fg = '#839496' })
hi(0, 'NeoTreeTabSeparatorActive', { bg = '#586e75', fg = '#657b83' })
hi(0, 'NeoTreeTabSeparatorInactive', { bg = '#073642', fg = '#073642' })
hi(0, 'NeogitCommitViewHeader', { link = 'Special' })
hi(0, 'NeogitDiffAdd', { link = 'DiffAdd' })
hi(0, 'NeogitDiffAddHighlight', { link = 'DiffAdd' })
hi(0, 'NeogitDiffDelete', { link = 'DiffDelete' })
hi(0, 'NeogitDiffDeleteHighlight', { link = 'DiffDelete' })
hi(0, 'NeogitFold', { link = 'FoldColumn' })
hi(0, 'NeogitHunkHeader', { fg = '#268bd2' })
hi(0, 'NeogitHunkHeaderHighlight', { bold = true, fg = '#268bd2' })
hi(0, 'NeogitNotificationError', { link = 'DiagnosticError' })
hi(0, 'NeogitNotificationInfo', { link = 'DiagnosticInfo' })
hi(0, 'NeogitNotificationWarning', { link = 'DiagnosticWarn' })
hi(0, 'NoiceCmdlinePopupBorder', { fg = '#268bd2' })
hi(0, 'NoiceConfirmBorder', { fg = '#6c71c4' })
hi(0, 'NonText', { fg = '#657b83' })
hi(0, 'Normal', { bg = '#002b36', fg = '#93a1a1' })
hi(0, 'NormalFloat', { bg = '#073642', fg = '#93a1a1' })
hi(0, 'NormalNC', { bg = '#002b36', fg = '#93a1a1' })
hi(0, 'NotifyDEBUGBorder', { fg = '#657b83' })
hi(0, 'NotifyDEBUGIcon', { link = 'NotifyDEBUGBorder' })
hi(0, 'NotifyDEBUGTitle', { link = 'NotifyDEBUGBorder' })
hi(0, 'NotifyERRORBorder', { fg = '#dc322f' })
hi(0, 'NotifyERRORIcon', { link = 'NotifyERRORBorder' })
hi(0, 'NotifyERRORTitle', { link = 'NotifyERRORBorder' })
hi(0, 'NotifyINFOBorder', { fg = '#2aa198' })
hi(0, 'NotifyINFOIcon', { link = 'NotifyINFOBorder' })
hi(0, 'NotifyINFOTitle', { link = 'NotifyINFOBorder' })
hi(0, 'NotifyTRACEBorder', { fg = '#268bd2' })
hi(0, 'NotifyTRACEIcon', { link = 'NotifyTRACEBorder' })
hi(0, 'NotifyTRACETitle', { link = 'NotifyTRACEBorder' })
hi(0, 'NotifyWARNBorder', { fg = '#6c71c4' })
hi(0, 'NotifyWARNIcon', { link = 'NotifyWARNBorder' })
hi(0, 'NotifyWARNTitle', { link = 'NotifyWARNBorder' })
hi(0, 'Number', { fg = '#839496' })
hi(0, 'NvimTreeExecFile', { bold = true, fg = '#859900' })
hi(0, 'NvimTreeFolderIcon', { fg = '#657b83' })
hi(0, 'NvimTreeGitDeleted', { fg = '#dc322f' })
hi(0, 'NvimTreeGitDirty', { fg = '#dc322f' })
hi(0, 'NvimTreeGitMerge', { fg = '#2aa198' })
hi(0, 'NvimTreeGitNew', { fg = '#b58900' })
hi(0, 'NvimTreeGitRenamed', { fg = '#6c71c4' })
hi(0, 'NvimTreeGitStaged', { fg = '#859900' })
hi(0, 'NvimTreeImageFile', { bold = true, fg = '#6c71c4' })
hi(0, 'NvimTreeIndentMarker', { link = 'NvimTreeFolderIcon' })
hi(0, 'NvimTreeOpenedFile', { link = 'NvimTreeExecFile' })
hi(0, 'NvimTreeRootFolder', { link = 'NvimTreeGitRenamed' })
hi(0, 'NvimTreeSpecialFile', { bold = true, fg = '#268bd2', underline = true })
hi(0, 'NvimTreeSymlink', { bold = true, fg = '#d33682' })
hi(0, 'NvimTreeWindowPicker', { bg = '#073642', bold = true, fg = '#93a1a1' })
hi(0, 'Operator', { fg = '#93a1a1' })
hi(0, 'OutlineDetail', { fg = '#657b83' })
hi(0, 'OutlineFoldPrefix', { fg = '#dc322f' })
hi(0, 'OutlineIndentEvn', { fg = '#839496' })
hi(0, 'OutlineIndentOdd', { fg = '#93a1a1' })
hi(0, 'Pmenu', { bg = '#073642', fg = '#93a1a1' })
hi(0, 'PmenuSbar', { bg = '#586e75' })
hi(0, 'PmenuSel', { bg = '#93a1a1', blend = 0, fg = '#073642' })
hi(0, 'PmenuThumb', { bg = '#fdf6e3' })
hi(0, 'PounceAccept', { bg = '#dc322f', bold = true, fg = '#002b36', nocombine = true })
hi(0, 'PounceAcceptBest', { bg = '#859900', bold = true, fg = '#002b36', nocombine = true })
hi(0, 'PounceGap', { bg = '#657b83', bold = true, fg = '#002b36', nocombine = true })
hi(0, 'PounceMatch', { bg = '#93a1a1', bold = true, fg = '#002b36', nocombine = true })
hi(0, 'PreCondit', { fg = '#b58900' })
hi(0, 'PreProc', { fg = '#b58900' })
hi(0, 'Question', { ctermfg = 14, fg = '#268bd2' })
hi(0, 'QuickFixLine', { bg = '#073642', ctermfg = 14 })
hi(0, 'RainbowDelimiterBlue', { fg = '#268bd2' })
hi(0, 'RainbowDelimiterCyan', { fg = '#2aa198' })
hi(0, 'RainbowDelimiterGreen', { fg = '#859900' })
hi(0, 'RainbowDelimiterOrange', { fg = '#cb4b16' })
hi(0, 'RainbowDelimiterRed', { fg = '#dc322f' })
hi(0, 'RainbowDelimiterViolet', { fg = '#6c71c4' })
hi(0, 'RainbowDelimiterYellow', { fg = '#b58900' })
hi(0, 'References', { fg = '#859900' })
hi(0, 'ReferencesIcon', { fg = '#268bd2' })
hi(0, 'Removed', { ctermfg = 9, fg = '#dc322f' })
hi(0, 'Repeat', { fg = '#b58900' })
hi(0, 'Search', { bg = '#b58900', ctermbg = 11, ctermfg = 0, fg = '#073642' })
hi(0, 'SignColumn', { bg = '#073642', fg = '#657b83' })
hi(0, 'Sneak', { bg = '#6c71c4', fg = '#002b36' })
hi(0, 'SneakLabel', { bg = '#6c71c4', bold = true, fg = '#002b36' })
hi(0, 'SneakScope', { bg = '#fdf6e3', fg = '#002b36' })
hi(0, 'Special', { fg = '#839496' })
hi(0, 'SpecialChar', { fg = '#839496' })
hi(0, 'SpecialComment', { fg = '#2aa198' })
hi(0, 'SpecialKey', { fg = '#657b83' })
hi(0, 'SpellBad', { sp = '#dc322f', undercurl = true })
hi(0, 'SpellCap', { sp = '#268bd2', undercurl = true })
hi(0, 'SpellLocal', { sp = '#2aa198', undercurl = true })
hi(0, 'SpellRare', { sp = '#6c71c4', undercurl = true })
hi(0, 'Statement', { fg = '#dc322f' })
hi(0, 'StatusLine', { bg = '#586e75', fg = '#839496' })
hi(0, 'StatusLineNC', { bg = '#073642', fg = '#657b83' })
hi(0, 'StorageClass', { fg = '#b58900' })
hi(0, 'String', { fg = '#839496' })
hi(0, 'Structure', { fg = '#6c71c4' })
hi(0, 'Substitute', { bg = '#b58900', fg = '#073642' })
hi(0, 'TabLine', { bg = '#073642', fg = '#657b83' })
hi(0, 'TabLineFill', { bg = '#073642', fg = '#657b83' })
hi(0, 'TabLineSel', { bg = '#073642', fg = '#859900' })
hi(0, 'Tag', { fg = '#b58900' })
hi(0, 'TargetFileName', { fg = '#93a1a1' })
hi(0, 'TelescopeBorder', { fg = '#d33682' })
hi(0, 'TelescopeMatching', { fg = '#b58900' })
hi(0, 'TelescopeMultiSelection', { bg = '#073642', bold = true })
hi(0, 'TelescopeSelection', { bg = '#073642', bold = true })
hi(0, 'TermCursorNC', { reverse = true })
hi(0, 'Title', { fg = '#268bd2' })
hi(0, 'Todo', { bg = '#073642', fg = '#b58900' })
hi(0, 'TooLong', { fg = '#dc322f' })
hi(0, 'TroubleCount', { bold = true, fg = '#859900' })
hi(0, 'TroubleFoldIcon', { fg = '#93a1a1' })
hi(0, 'TroubleIndent', { fg = '#586e75' })
hi(0, 'TroubleLocation', { fg = '#839496' })
hi(0, 'TroubleSignError', { link = 'DiagnosticError' })
hi(0, 'TroubleSignHint', { link = 'DiagnosticHint' })
hi(0, 'TroubleSignInformation', { link = 'DiagnosticInfo' })
hi(0, 'TroubleSignOther', { link = 'DiagnosticInfo' })
hi(0, 'TroubleSignWarning', { link = 'DiagnosticWarn' })
hi(0, 'TroubleText', { fg = '#93a1a1' })
hi(0, 'TroubleTextError', { link = 'TroubleText' })
hi(0, 'TroubleTextHint', { link = 'TroubleText' })
hi(0, 'TroubleTextInformation', { link = 'TroubleText' })
hi(0, 'TroubleTextWarning', { link = 'TroubleText' })
hi(0, 'Type', { fg = '#839496' })
hi(0, 'Typedef', { fg = '#b58900' })
hi(0, 'VertSplit', { bg = '#586e75', fg = '#586e75' })
hi(0, 'Visual', { bg = '#586e75', ctermbg = 15, ctermfg = 0 })
hi(0, 'VisualNOS', { fg = '#dc322f' })
hi(0, 'WarningMsg', { ctermfg = 11, fg = '#dc322f' })
hi(0, 'WhichKey', { fg = '#268bd2' })
hi(0, 'WhichKeyDesc', { fg = '#93a1a1' })
hi(0, 'WhichKeyFloat', { bg = '#073642', fg = '#93a1a1' })
hi(0, 'WhichKeyGroup', { fg = '#6c71c4' })
hi(0, 'WhichKeySeparator', { bg = '#073642', fg = '#859900' })
hi(0, 'WhichKeyValue', { fg = '#657b83' })
hi(0, 'Whitespace', { fg = '#657b83' })
hi(0, 'WildMenu', { bg = '#b58900', fg = '#dc322f' })
hi(0, 'WinBar', { bg = '#586e75', fg = '#839496' })
hi(0, 'WinBarNC', { bg = '#073642', fg = '#657b83' })
hi(0, 'WinSeparator', { bg = '#586e75', fg = '#586e75' })
hi(0, 'diffAdded', { fg = '#859900' })
hi(0, 'diffChanged', { fg = '#6c71c4' })
hi(0, 'diffFile', { fg = '#cb4b16' })
hi(0, 'diffLine', { fg = '#2aa198' })
hi(0, 'diffRemoved', { fg = '#dc322f' })
hi(0, 'gitcommitBranch', { bold = true, fg = '#cb4b16' })
hi(0, 'gitcommitComment', { link = 'Comment' })
hi(0, 'gitcommitDiscarded', { link = 'Comment' })
hi(0, 'gitcommitDiscardedFile', { bold = true, fg = '#dc322f' })
hi(0, 'gitcommitDiscardedType', { fg = '#268bd2' })
hi(0, 'gitcommitHeader', { fg = '#6c71c4' })
hi(0, 'gitcommitOverflow', { fg = '#dc322f' })
hi(0, 'gitcommitSelected', { link = 'Comment' })
hi(0, 'gitcommitSelectedFile', { bold = true, fg = '#859900' })
hi(0, 'gitcommitSelectedType', { link = 'gitcommitDiscardedType' })
hi(0, 'gitcommitSummary', { fg = '#859900' })
hi(0, 'gitcommitUnmergedFile', { link = 'gitcommitDiscardedFile' })
hi(0, 'gitcommitUnmergedType', { link = 'gitcommitDiscardedType' })
hi(0, 'gitcommitUntracked', { link = 'Comment' })
hi(0, 'gitcommitUntrackedFile', { fg = '#b58900' })
hi(0, 'lCursor', { bg = '#93a1a1', fg = '#002b36' })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = '#002b36'
g.terminal_color_1 = '#dc322f'
g.terminal_color_2 = '#859900'
g.terminal_color_3 = '#b58900'
g.terminal_color_4 = '#268bd2'
g.terminal_color_5 = '#6c71c4'
g.terminal_color_6 = '#2aa198'
g.terminal_color_7 = '#93a1a1'
g.terminal_color_8 = '#657b83'
g.terminal_color_9 = '#dc322f'
g.terminal_color_10 = '#859900'
g.terminal_color_11 = '#b58900'
g.terminal_color_12 = '#268bd2'
g.terminal_color_13 = '#6c71c4'
g.terminal_color_14 = '#2aa198'
g.terminal_color_15 = '#fdf6e3'
